#!/usr/bin/env python3
"""Week-specific V13 content specs for C2-W1..C2-W6 and C3-W1..C3-W6."""
from __future__ import annotations

# Primary mechanic must match V13-ACTIVITY-VARIETY-MATRIX.md (no consecutive identical).

SPECS: dict[str, dict] = {
    "C2-W1": {
        "mechanic": "Cause-effect map",
        "memory": "Choices are seeds. I want to plant service seeds.",
        "adult_memory": "Work for Viṣṇu without selfish attachment; otherwise action binds.",
        "eq": "How do our actions bind or free us?",
        "conclusion": "Action with selfish attachment binds; action for the Lord’s purpose can be purified.",
        "misconception": "Fatalism removes responsibility; do not diagnose others’ hardship as specific past karma.",
        "care_boundary": "No victim-blaming. No graphic hell imagery with children.",
        "home_min": "memory line once + Before–During–After on one routine duty",
        "next_week": "C2-W2 — Free Will and Responsibility: The Next Choice Matters",
        "project_line": "Family action–intention–consequence card for one household duty",
        "dev": "यज्ञार्थात्कर्मणोऽन्यत्र लोकोऽयं कर्मबन्धनः । तदर्थं कर्म कौन्तेय मुक्तसङ्गः समाचर ॥ ९ ॥",
        "iast": "yajñārthāt karmaṇo ’nyatra loko ’yaṁ karma-bandhanaḥ / tad-arthaṁ karma kaunteya mukta-saṅgaḥ samācara",
        "meaning": "Work done for the satisfaction of the Lord frees us from bondage; otherwise action binds. Therefore act with detachment for His purpose.",
        "y": [
            ("Y01-DOMINO-PATH-CARDS", "Domino / cause-effect path (limits)", "Place domino cards: action → next → result. Say the limit aloud."),
            ("Y02-SEED-CHOICE-MATCHING", "Seed choice matching", "Match planting pictures to kind/service vs sharp/selfish seeds."),
            ("Y03-BEFORE-DURING-AFTER-CRAFT", "Before–During–After craft", "Fold a three-panel card for one small help at home."),
            ("Y04-SOFT-WORDS-CARDS", "Soft-words redirect cards", "After hot words, point to a soft repair card."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Tap each line while echoing the memory phrase."),
        ],
        "o": [
            ("O01-BG-3-9-OBSERVATION", "BG 3.9 observation", "Observe verse layers; paraphrase; name what the verse does not authorize."),
            ("O02-ACTION-INTENTION-CONSEQUENCE-MAP", "Action → intention → consequence map", "Fill three boxes for a school/home scenario."),
            ("O03-SERVICE-VS-SELFISH-SORT", "Service vs selfish-attachment sort", "Sort cards; discuss almost-right traps."),
            ("O04-CHOICE-CONSEQUENCE-SCENARIOS", "Choice–consequence scenarios", "Work three cases with principle + better action."),
            ("O05-BEFORE-DURING-AFTER-DIAGRAM", "Before–During–After diagram", "Map one duty with offered intention."),
            ("O06-EXIT-TICKET", "Exit ticket", "One-sentence paraphrase + one home action."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — binding speech/habits", "Where does our home act for face/control rather than service?"),
            ("P02-CONSEQUENCE-CASE-CARD-SORT", "Consequence case card sort", "Sort RESPONSIBLE REPAIR vs MISTAKEN DIAGNOSIS."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Public blame text after a missed pickup."),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One Before–During–After duty for seven days."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Specific action + frequency + trigger + minimum version."),
        ],
        "pngs": ["cause-effect-path.png", "seed-cards.png", "bda-panels.png", "memory-mat.png", "parent-consequence.png"],
        "cards_y": ["Plant a help seed", "Send a sharp text seed", "Share a toy seed", "Hide a mess seed", "Say sorry seed", "Blame loudly seed"],
        "cards_o_sort": ["Quiet kitchen help", "Gift for applause", "Repair private apology", "Diagnose cousin’s illness as karma", "Offer food first", "Win the argument at all costs"],
        "parent_case": "After a missed pickup, a parent sends a sharp group-chat blame message copying relatives. The logistics need was real; the public heat was extra.",
    },
    "C2-W2": {
        "mechanic": "Decision tree",
        "memory": "The next choice matters.",
        "adult_memory": "Deliberate fully, then act as you choose — responsibility remains with you.",
        "eq": "What is my next responsible choice?",
        "conclusion": "Knowledge invites deliberation; the living being still chooses; the next choice matters.",
        "misconception": "Choice means do whatever you feel; OR the soul has no agency / “I had no choice.”",
        "care_boundary": "Do not blame children for events beyond their control; distinguish agency from total control.",
        "home_min": "memory line once + name one next responsible choice for tomorrow morning",
        "next_week": "C2-W3 — Birth, Death and Reincarnation",
        "project_line": "Family next-choice decision tree for one recurring fork",
        "dev": "इति ते ज्ञानमाख्यातं गुह्याद्गुह्यतरं मया । विमृश्यैतदशेषेण यथेच्छसि तथा कुरु ॥ ६३ ॥",
        "iast": "iti te jñānam ākhyātaṁ guhyād guhyataraṁ mayā / vimṛśyaitad aśeṣeṇa yathecchasi tathā kuru",
        "meaning": "The Lord has explained confidential knowledge; now deliberate fully and then act as you choose — responsibility remains with the living being.",
        "y": [
            ("Y01-FORK-IN-ROAD-MOVEMENT", "Fork-in-road movement", "Walk left/right forks for kind vs sharp next choice."),
            ("Y02-NEXT-CHOICE-MATCHING", "Next-choice matching", "Match situations to better next steps."),
            ("Y03-CHOICE-TREE-CRAFT", "Simple choice-tree craft", "Draw two branches from one fork."),
            ("Y04-AGENCY-CARE-CARDS", "Agency + care cards", "Cards: I can choose / I need help / Not my fault."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo: The next choice matters."),
        ],
        "o": [
            ("O01-BG-18-63-OBSERVATION", "BG 18.63 observation", "Observe deliberation + choice language."),
            ("O02-NEXT-CHOICE-DECISION-TREE", "Next-choice decision tree", "Build a 3-level tree for a real low-risk fork."),
            ("O03-AGENCY-VS-CONTROL-SORT", "Agency vs control sort", "Sort what I can choose / influence / not control."),
            ("O04-RESPONSIBILITY-SCENARIOS", "Responsibility scenarios", "Three cases: blame, freeze, responsible next step."),
            ("O05-DELIBERATION-WORKSHEET", "Deliberation worksheet", "vimṛśya practice: facts, options, values, choose."),
            ("O06-EXIT-TICKET", "Exit ticket", "My next responsible choice tomorrow."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — agency vs control", "Where do we confuse control with responsibility?"),
            ("P02-AGENCY-CONTROL-CARD-SORT", "Agency vs control card sort", "Sort CAN CHOOSE / CAN INFLUENCE / CANNOT CONTROL."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Teen freezes after a grade drop; parent says “you had no choice but to fail.”"),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One nightly deliberation cue for seven days."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Specific next choice + trigger + minimum version."),
        ],
        "pngs": ["fork-road.png", "decision-tree.png", "agency-rings.png", "memory-mat.png", "parent-agency.png"],
        "cards_y": ["Share now", "Grab first", "Ask for help", "Hide the mess", "Say the truth kindly", "Blame a sibling"],
        "cards_o_sort": ["My tone in an argument", "Traffic delay", "Sibling’s mood", "Whether I apologize", "Weather", "My homework start time"],
        "parent_case": "A teen freezes after a grade drop. One parent says “you had no choice but to fail.” Another lectures for twenty minutes without naming a next step.",
    },
    "C2-W3": {
        "mechanic": "Analogy with limits",
        "memory": "Birth and death are changes of dress for the eternal self.",
        "adult_memory": "Speak calmly: the embodied self continues; analogies have limits; no scare pedagogy.",
        "eq": "How do we speak calmly about birth and death?",
        "conclusion": "The clothing analogy teaches continuity with limits; families speak with calm dignity, not fear.",
        "misconception": "Scare pedagogy; diagnosing destinations; ghost speculation; closet-shopping for bodies.",
        "care_boundary": "Age-sensitive death talk; no frightening imagery; no unsupported past-life anecdotes.",
        "home_min": "memory line once + one calm gratitude sentence for life/care",
        "next_week": "C2-W4 — The Three Modes of Material Nature",
        "project_line": "Family calm-speech card for life-change conversations",
        "dev": "वासांसि जीर्णानि यथा विहाय नवानि गृह्णाति नरोऽपराणि । तथा शरीराणि विहाय जीर्णान्यन्यानि संयाति नवानि देही ॥ २२ ॥",
        "iast": "vāsāṁsi jīrṇāni yathā vihāya navāni gṛhṇāti naro ’parāṇi / tathā śarīrāṇi vihāya jīrṇāny anyāni saṁyāti navāni dehī",
        "meaning": "As a person puts on new garments, giving up old ones, the embodied self similarly accepts new bodies, giving up old ones — taught calmly, without fear tactics for children.",
        "y": [
            ("Y01-GENTLE-CLOTHES-CHANGE", "Gentle clothes-change sequence", "Order worn shirt → folded shirt → new shirt; say the limit."),
            ("Y02-SAME-FRIEND-CARE-MATCHING", "Same-friend care matching", "Match care acts that honor a person who changes."),
            ("Y03-CALM-HEART-CRAFT", "Calm-heart craft", "Draw a calm heart for kind words about change."),
            ("Y04-GENTLE-WORDS-CARDS", "Gentle words cards", "Redirect scare talk to gentle cards."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo the dress-change memory line gently."),
        ],
        "o": [
            ("O01-BG-2-22-OBSERVATION", "BG 2.22 observation", "Observe analogy language and its classroom limits."),
            ("O02-ANALOGY-LIMITS-WORKSHEET", "Analogy + limits worksheet", "Map garment analogy; write where it breaks."),
            ("O03-CALM-VS-SCARE-SORT", "Calm vs scare speech sort", "Sort respectful teaching vs fear tactics."),
            ("O04-AGE-SENSITIVE-SCENARIOS", "Age-sensitive scenarios", "Three family talk scenarios with boundaries."),
            ("O05-CONTINUITY-CARE-DIAGRAM", "Continuity + care diagram", "Self continues; body deserves care."),
            ("O06-EXIT-TICKET", "Exit ticket", "One analogy + one limit + one calm sentence."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — how we talk about death", "What scare or silence patterns do we use?"),
            ("P02-CALM-SPEECH-CARD-SORT", "Calm speech card sort", "Sort CALM / SCARE / SPECULATION."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Child asks about a grandparent’s death at dinner."),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One calm-response line + who speaks first."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Practice one calm conversation cue."),
        ],
        "pngs": ["clothes-change.png", "analogy-limits.png", "calm-heart.png", "memory-mat.png", "parent-calm-talk.png"],
        "cards_y": ["Fold old shirt", "Put on fresh shirt", "Say a kind thank-you", "Scare story", "Hug a friend", "Guess a ghost tale"],
        "cards_o_sort": ["Bodies change like clothes (with limits)", "Frighten kids into belief", "We care for elders", "Diagnose someone’s destination", "Photos prove reincarnation", "Speak gently about loss"],
        "parent_case": "At dinner a child asks where a grandparent “went.” One adult freezes. Another launches into graphic afterlife details and a destination diagnosis.",
    },
    "C2-W4": {
        "mechanic": "Scenario sorting",
        "memory": "Calm helps me hear Kṛṣṇa.",
        "adult_memory": "Modes shape moments — never label a person “a mode.”",
        "eq": "Which mode is shaping this moment?",
        "conclusion": "Sattva, rajas, and tamas condition the embodied self; notice the moment; design supports; never label persons.",
        "misconception": "Labeling people/families as a mode; food policing as spiritual superiority.",
        "care_boundary": "Never label persons. Avoid food policing. Environment supports practice; devotion is the goal.",
        "home_min": "memory line once + one five-minute environment reset before chanting/reading",
        "next_week": "C2-W5 — Māyā: Decorating the Prison Cell",
        "project_line": "Family mode-moment notice board (moments, not people)",
        "dev": "सत्त्वं रजस्तम इति गुणा: प्रकृतिसम्भवा: । निबध्नन्ति महाबाहो देहे देहिनमव्ययम् ॥ ५ ॥",
        "iast": "sattvaṁ rajas tama iti guṇāḥ prakṛti-sambhavāḥ / nibadhnanti mahā-bāho dehe dehinam avyayam",
        "meaning": "Goodness, passion, and ignorance — born of material nature — bind the eternal embodied self within the body.",
        "y": [
            ("Y01-MODE-WEATHER-CORNERS", "Mode weather corners", "Sunny/windy/foggy corners for calm/busy/sleepy moments — not people."),
            ("Y02-MOMENT-MATCHING", "Moment matching", "Match scenes to weather icons."),
            ("Y03-RESET-CORNER-CRAFT", "Reset-corner craft", "Make a calm-corner card for home."),
            ("Y04-KIND-RESET-CARDS", "Kind reset cards", "Words for resetting a chaotic room."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo: Calm helps me hear Kṛṣṇa."),
        ],
        "o": [
            ("O01-BG-14-5-OBSERVATION", "BG 14.5 observation", "Name three modes; what they do; what they are not."),
            ("O02-MODE-SCENARIO-BOARD", "Mode scenario board", "Sort scenarios into moment influences."),
            ("O03-SUPPORT-VS-LABEL-SORT", "Support vs label sort", "Helpful environment support vs person-labeling."),
            ("O04-HABIT-ENVIRONMENT-SCENARIOS", "Habit/environment scenarios", "Three household chaos/clarity cases."),
            ("O05-CLARITY-BEFORE-CHANTING-DIAGRAM", "Clarity-before-chanting diagram", "Reset → practice → review."),
            ("O06-EXIT-TICKET", "Exit ticket", "One moment notice + one support + no person label."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — habit environment", "Which room cues push restless or dull moments?"),
            ("P02-SUPPORT-VS-LABEL-CARD-SORT", "Support vs label card sort", "Sort SUPPORT / LABELING / FOOD POLICING."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Parent calls a child “tamasic” after late screens."),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One five-minute reset ritual for seven days."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Environment support + minimum version."),
        ],
        "pngs": ["mode-weather.png", "scenario-board.png", "clarity-reset.png", "memory-mat.png", "parent-environment.png"],
        "cards_y": ["Sunny calm", "Windy rush", "Foggy sleepy", "Reset corner", "Quiet voice", "Call someone a mode"],
        "cards_o_sort": ["Clear the table before reading", "You are tamasic", "Dim lights for bedtime", "Our family is rajasic", "Phone basket at door", "Food police lecture"],
        "parent_case": "After late screens, a parent announces “you’re being tamasic again” in front of siblings. The child shuts down; another parent starts food policing as spiritual ranking.",
    },
    "C2-W5": {
        "mechanic": "Attention trap cases",
        "memory": "Surrender crosses māyā.",
        "adult_memory": "Māyā is difficult to overcome; surrender to Kṛṣṇa is the crossing — not paranoia or willpower alone.",
        "eq": "Where are we decorating bondage?",
        "conclusion": "Illusory energy is hard to cross; surrender and Kṛṣṇa-centered practice open the path — without fear pedagogy.",
        "misconception": "Hate all material duty / “women are māyā”; willpower alone conquers māyā without surrender.",
        "care_boundary": "Age-sensitive; no fear/paranoia; decorating-prison analogy with limits.",
        "home_min": "memory line once + one attention-audit minute before screens/chanting",
        "next_week": "C2-W6 — Integration Night: Choice, Consequence and the Modes",
        "project_line": "Family attention-trap / escape-path card",
        "dev": "दैवी ह्येषा गुणमयी मम माया दुरत्यया । मामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते ॥ १४ ॥",
        "iast": "daivī hy eṣā guṇa-mayī mama māyā duratyayā / mām eva ye prapadyante māyām etāṁ taranti te",
        "meaning": "This divine illusory energy of the Lord, made of the modes, is difficult to overcome — but those who surrender unto Him cross beyond it.",
        "y": [
            ("Y01-TRAP-ESCAPE-PATH", "Simple trap/escape path", "Follow path: shiny trap → pause → call Kṛṣṇa / kind help."),
            ("Y02-SHINY-VS-REAL-MATCHING", "Shiny vs real matching", "Match ads/toys to “looks big” vs “helps love.”"),
            ("Y03-ESCAPE-LANTERN-CRAFT", "Escape lantern craft", "Craft a lantern card for holy name / help."),
            ("Y04-PAUSE-CARDS", "Pause cards", "When stuck, point to Pause / Ask / Chant."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo: Surrender crosses māyā."),
        ],
        "o": [
            ("O01-BG-7-14-OBSERVATION", "BG 7.14 observation", "Observe difficulty + surrender crossing."),
            ("O02-ADVERTISING-ILLUSION-BOARD", "Advertising illusion board", "Map attention traps and better aims."),
            ("O03-TRAP-VS-ESCAPE-SORT", "Trap vs escape sort", "Sort decorating-bondage vs crossing helps."),
            ("O04-ATTENTION-TRAP-SCENARIOS", "Attention trap scenarios", "Three low-risk family attention cases."),
            ("O05-ESCAPE-MAP-DIAGRAM", "Escape-map diagram", "Notice → turn → shelter in Kṛṣṇa practice."),
            ("O06-EXIT-TICKET", "Exit ticket", "One trap I notice + one surrender practice."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — attention audit", "Where do we decorate comfort while neglecting devotion?"),
            ("P02-ATTENTION-AUDIT-CARD-SORT", "Attention audit card sort", "Sort TRAP / CROSSING HELP / HARMFUL FRAMING."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Family upgrades gadgets weekly while skipping shared chanting."),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One attention-audit cue + one chanting shelter."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Surrender practice + minimum version."),
        ],
        "pngs": ["trap-escape-path.png", "illusion-board.png", "escape-lantern.png", "memory-mat.png", "parent-attention.png"],
        "cards_y": ["Shiny toy shout", "Pause", "Ask for help", "Holy name", "Scare story", "Kind share"],
        "cards_o_sort": ["Endless upgrade chase", "Short holy name", "Women are māyā", "Willpower alone", "Serve quietly", "Paranoia about all matter"],
        "parent_case": "A family keeps upgrading gadgets and rearranging décor while shared chanting disappears. One adult jokes “we’re just making the prison nicer.” Another says “all duty is māyā — quit your job.”",
    },
    "C2-W6": {
        "mechanic": "Scenario board teach-back",
        "memory": "Choose with all five lenses.",
        "adult_memory": "Integrate choice, consequence, and modes — no major new doctrine.",
        "eq": "Can we synthesize choice and modes?",
        "conclusion": "Cycle 2 becomes one family practice: responsible choice, consequence awareness, mode supports — taught back without ranking.",
        "misconception": "Integration means new advanced doctrine; ranking families by presentation polish.",
        "care_boundary": "Retrieval/presentation focus; no major new doctrine; noncompetitive teach-back.",
        "home_min": "memory line once + one family teach-back sentence of Cycle 2",
        "next_week": "C2 Utsava — Gītā Jayantī Family Utsava (festival prep; local tithi EXTERNAL_OPEN)",
        "project_line": "Cycle 2 teach-back board / family presentation cue card",
        "dev": "इति ते ज्ञानमाख्यातं गुह्याद्गुह्यतरं मया । विमृश्यैतदशेषेण यथेच्छसि तथा कुरु ॥ ६३ ॥",
        "iast": "iti te jñānam ākhyātaṁ guhyād guhyataraṁ mayā / vimṛśyaitad aśeṣeṇa yathecchasi tathā kuru",
        "meaning": "Choice, consequence, and the modes must form one coherent family practice — synthesis, not new doctrine overload. (BG 18.63 center for review.)",
        "y": [
            ("Y01-REVIEW-GAME-STATIONS", "Review game stations", "Visit karma / choice / dress / weather / escape stations."),
            ("Y02-LENS-MATCHING", "Five-lens matching", "Match icons to Cycle 2 themes."),
            ("Y03-TEACH-BACK-CRAFT", "Teach-back craft", "One sentence our family can teach."),
            ("Y04-CHEER-CARDS", "Cheer cards", "Encourage other families without ranking."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo: Choose with all five lenses."),
        ],
        "o": [
            ("O01-CYCLE2-RETRIEVAL", "Cycle 2 retrieval quiz", "Retrieve BG 3.9 / 18.63 / 2.22 / 14.5 / 7.14 themes."),
            ("O02-CHOICE-MODES-BOARD", "Choice + modes board", "Place scenarios on choice/consequence/mode board."),
            ("O03-MISCONCEPTION-CLINIC", "Misconception clinic", "Correct fatalism, labeling, scare talk, paranoia."),
            ("O04-TEACH-BACK-SCENARIOS", "Teach-back scenarios", "Coach a 2-minute family teach-back."),
            ("O05-INTEGRATION-DIAGRAM", "Integration diagram", "Five lenses → one household practice."),
            ("O06-EXIT-TICKET", "Exit ticket", "One synthesis sentence + one home cue."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — what stuck", "Which Cycle 2 lens most needs household practice?"),
            ("P02-TEACH-BACK-CARD-SORT", "Teach-back card sort", "Sort RETRIEVAL / APPLICATION / RANKING (avoid)."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Family wants to impress with a polished speech and skip retrieval."),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One teach-back sentence + practice night."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Integration practice for seven days."),
        ],
        "pngs": ["five-lens-board.png", "retrieval-stations.png", "teach-back.png", "memory-mat.png", "parent-integration.png"],
        "cards_y": ["Karma seed", "Next choice", "Dress change", "Mode weather", "Escape path", "Trophy ranking"],
        "cards_o_sort": ["Retrieve a verse theme", "Apply at home", "Rank families", "Correct a misconception", "New advanced doctrine dump", "Cheer another family"],
        "parent_case": "A family rehearses a polished speech to impress others and skips retrieving the actual Cycle 2 verse themes. Children worry about “winning” Integration Night.",
    },
    "C3-W1": {
        "mechanic": "Triple-lens map",
        "memory": "Kṛṣṇa owns, enjoys, befriends.",
        "adult_memory": "Knowing God as enjoyer, proprietor, and friend brings peace into ownership and service.",
        "eq": "Who is God — and how does knowing Him bring peace?",
        "conclusion": "Kṛṣṇa is supreme enjoyer, proprietor of all worlds, and friend of all beings — knowing this brings peace.",
        "misconception": "God as remote force only; ownership means domination without friendship/service.",
        "care_boundary": "Age-appropriate ownership/friendship/service; no speculative iconography.",
        "home_min": "memory line once + one act of care for something we steward for Kṛṣṇa",
        "next_week": "C3-W2 — Who Is Kṛṣṇa? The Supreme Personality of Godhead",
        "project_line": "Family three-lens map (enjoyer / proprietor / friend)",
        "dev": "भोक्तारं यज्ञतपसां सर्वलोकमहेश्वरम् । सुहृदं सर्वभूतानां ज्ञात्वा मां शान्तिमृच्छति ॥ २९ ॥",
        "iast": "bhoktāraṁ yajña-tapasāṁ sarva-loka-maheśvaram / suhṛdaṁ sarva-bhūtānāṁ jñātvā māṁ śāntim ṛcchati",
        "meaning": "Knowing Kṛṣṇa as the supreme enjoyer of sacrifice and austerity, the Lord of all worlds, and the friend of all beings, one attains peace.",
        "y": [
            ("Y01-THREE-LENS-ICONS", "Enjoyer/owner/friend icons", "Place three icon cards; say each lens."),
            ("Y02-LENS-MATCHING", "Lens matching", "Match home scenes to enjoyer/owner/friend."),
            ("Y03-FRIEND-OF-ALL-CRAFT", "Friend-of-all craft", "Craft a friend-heart for kind service."),
            ("Y04-STEWARD-CARDS", "Steward cards", "We care for things because Kṛṣṇa owns."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo: Kṛṣṇa owns, enjoys, befriends."),
        ],
        "o": [
            ("O01-BG-5-29-OBSERVATION", "BG 5.29 observation", "Three titles → peace."),
            ("O02-THREE-LENS-WORKSHEET", "Three-lens worksheet", "Map enjoyer / proprietor / friend applications."),
            ("O03-OWNERSHIP-SERVICE-SORT", "Ownership/service sort", "Sort domination vs stewardship."),
            ("O04-PEACE-APPLICATION-SCENARIOS", "Peace application scenarios", "Three ownership conflict cases."),
            ("O05-TRIPLE-LENS-DIAGRAM", "Triple-lens diagram", "One Lord; three lenses; peace."),
            ("O06-EXIT-TICKET", "Exit ticket", "One lens to practice at home."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — ownership tone", "Where does our home clutch rather than steward?"),
            ("P02-OWNERSHIP-SERVICE-CARD-SORT", "Ownership/service card sort", "Sort STEWARD / CLUTCH / FRIEND."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Sibling fight over “my room / my phone.”"),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One stewardship sentence + one friend act."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Practice one lens daily."),
        ],
        "pngs": ["three-lens-map.png", "lens-icons.png", "friend-heart.png", "memory-mat.png", "parent-steward.png"],
        "cards_y": ["Enjoyer", "Owner", "Friend", "Share kindly", "Grab and shout mine", "Care for a plant"],
        "cards_o_sort": ["Offer first", "Dominate siblings", "Steward shared space", "Kṛṣṇa is only a force", "Befriend with service", "Clutch the remote"],
        "parent_case": "Siblings fight over “my room” and “my phone.” Parents escalate ownership lectures without naming Kṛṣṇa as proprietor or modeling friendship.",
    },
    "C3-W2": {
        "mechanic": "Source identity",
        "memory": "Nothing is above Kṛṣṇa.",
        "adult_memory": "Śāstra presents Kṛṣṇa as supreme; speak with reverence, not aggression.",
        "eq": "Why does śāstra present Kṛṣṇa as supreme — and how do we speak that with reverence, not aggression?",
        "conclusion": "There is no truth superior to Kṛṣṇa; everything rests upon Him — taught from sources with reverence.",
        "misconception": "Aggressive debate identity; speculative iconography/theology beyond sources.",
        "care_boundary": "Authorized sources only; no speculative theology; reverence over aggression.",
        "home_min": "memory line once + one reverent sentence about Kṛṣṇa from a source",
        "next_week": "C3-W3 — Guru, Sādhu and Śāstra",
        "project_line": "Family source-identity card (BG 7.7 thread analogy with limits)",
        "dev": "मत्त: परतरं नान्यत्किञ्चिदस्ति धनञ्जय । मयि सर्वमिदं प्रोतं सूत्रे मणिगणा इव ॥ ७ ॥",
        "iast": "mattaḥ parataraṁ nānyat kiñcid asti dhanañ-jaya / mayi sarvam idaṁ protaṁ sūtre maṇi-gaṇā iva",
        "meaning": "There is no truth superior to Kṛṣṇa; everything rests upon Him as pearls are strung on a thread.",
        "y": [
            ("Y01-WHO-IS-KRSNA-CUES", "Who-is-Kṛṣṇa picture cues", "Cue cards: flute/friend/protector — reverence, not jokes."),
            ("Y02-SOURCE-MATCHING", "Source matching", "Match “we learn from books/teachers” to listening."),
            ("Y03-THREAD-PEARL-CRAFT", "Thread-and-pearl craft", "Craft simple thread with beads — analogy with limits."),
            ("Y04-REVERENCE-CARDS", "Reverence cards", "Speak kindly about Kṛṣṇa; no mockery."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo: Nothing is above Kṛṣṇa."),
        ],
        "o": [
            ("O01-BG-7-7-OBSERVATION", "BG 7.7 observation", "Source identity of supremacy + thread analogy limits."),
            ("O02-SOURCE-OBSERVATION-WORKSHEET", "Source observation worksheet", "What the verse says / does not say."),
            ("O03-REVERENCE-VS-AGGRESSION-SORT", "Reverence vs aggression sort", "Sort speech postures."),
            ("O04-IDENTITY-APPLICATION-SCENARIOS", "Identity application scenarios", "Three school/home speech cases."),
            ("O05-THREAD-ANALOGY-DIAGRAM", "Thread analogy diagram", "Pearls on thread + limit box."),
            ("O06-EXIT-TICKET", "Exit ticket", "One source sentence + one reverence rule."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — how we speak of Kṛṣṇa", "Reverence or argument culture?"),
            ("P02-REVERENCE-CARD-SORT", "Reverence card sort", "Sort REVERENT / AGGRESSIVE / SPECULATIVE."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Teen wants to “win” a religion argument online."),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One reverence speech rule for seven days."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Source reading cue + minimum version."),
        ],
        "pngs": ["source-identity.png", "thread-pearls.png", "reverence-icons.png", "memory-mat.png", "parent-reverence.png"],
        "cards_y": ["Listen to a verse", "Joke about Deity", "Thread and pearls", "Kind prayer", "Yell to win", "Ask a teacher"],
        "cards_o_sort": ["Cite BG 7.7 calmly", "Win online fight", "Speculate freely", "Read with family", "Mock other faiths", "Reverent gratitude"],
        "parent_case": "A teen wants to “destroy” a classmate’s view online. Parents debate whether to coach winning rhetoric or reverent source-based speech.",
    },
    "C3-W3": {
        "mechanic": "Three-source verify",
        "memory": "Ask, serve, verify.",
        "adult_memory": "Receive knowledge with humility, inquiry, and service; verify with guru–sādhu–śāstra.",
        "eq": "How do we receive spiritual knowledge safely — and what can KUTUMBA not claim?",
        "conclusion": "Approach realized teachers with humility, inquiry, and service; verify; KUTUMBA is not a initiating guru.",
        "misconception": "Personality-cult framing; KUTUMBA claims of initiating authority; “I feel it so it is true.”",
        "care_boundary": "Age-appropriate authority boundaries; no personality cult; “I don’t know; I will verify.”",
        "home_min": "memory line once + one verify practice (“I will check the source”)",
        "next_week": "C3-W4 — Śrī Caitanya Mahāprabhu and the Holy Name",
        "project_line": "Family three-source verify card",
        "dev": "तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया । उपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः ॥ ३४ ॥",
        "iast": "tad viddhi praṇipātena paripraśnena sevayā / upadekṣyanti te jñānaṁ jñāninas tattva-darśinaḥ",
        "meaning": "Learn the truth by approaching a realized teacher with humility, sincere inquiry, and service — such seers of truth can impart knowledge.",
        "y": [
            ("Y01-ASK-CHECK-CARDS", "Ask-check cards", "Ask → listen → check with a trusted adult/book."),
            ("Y02-HUMBLE-HELP-MATCHING", "Humble help matching", "Match asking kindly to learning."),
            ("Y03-THREE-FRIENDS-CRAFT", "Three-friends craft", "Teacher / holy person example / book icons."),
            ("Y04-I-WILL-VERIFY-CARDS", "I-will-verify cards", "Practice the deferral sentence."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo: Ask, serve, verify."),
        ],
        "o": [
            ("O01-BG-4-34-OBSERVATION", "BG 4.34 observation", "Humility, inquiry, service triad."),
            ("O02-GURU-SADHU-SASTRA-CHECK", "Guru–sādhu–śāstra check", "Verify a claim with three-source map."),
            ("O03-SAFE-VS-UNSAFE-SORT", "Safe vs unsafe authority sort", "Sort healthy receiving vs cultish traps."),
            ("O04-VERIFY-PRACTICE-SCENARIOS", "Verify practice scenarios", "Three rumor/claim cases."),
            ("O05-RECEIVING-KNOWLEDGE-DIAGRAM", "Receiving-knowledge diagram", "Approach → inquire → serve → verify."),
            ("O06-EXIT-TICKET", "Exit ticket", "Deferral line + one verify habit."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — authority boundaries", "Where do we over-claim or under-verify?"),
            ("P02-VERIFY-PRACTICE-CARD-SORT", "Verify practice card sort", "Sort VERIFY / SPECULATE / OVERCLAIM."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Relative forwards a dramatic spiritual rumor as “must share.”"),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "Family verify phrase for seven days."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "One verify habit + minimum version."),
        ],
        "pngs": ["three-source-check.png", "ask-check-cards.png", "verify-path.png", "memory-mat.png", "parent-verify.png"],
        "cards_y": ["Ask kindly", "Guess loudly", "Check a book", "Serve a little", "Believe every video", "Say I will verify"],
        "cards_o_sort": ["Check śāstra", "Personality cult praise", "Ask a teacher", "Forward rumor", "KUTUMBA is my guru", "Defer and verify"],
        "parent_case": "A relative forwards a dramatic spiritual rumor as “must share tonight.” One parent wants to forward immediately; another wants to verify but feels rude.",
    },
    "C3-W4": {
        "mechanic": "Kīrtana etiquette",
        "memory": "Paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam.",
        "adult_memory": "Holy name cleanses the heart; practice with attention — volume ≠ devotion.",
        "eq": "What is śrī-kṛṣṇa-saṅkīrtanam — and how do families practice it with attention, not performance pressure?",
        "conclusion": "All glory to śrī-kṛṣṇa-saṅkīrtana; families practice with attention and etiquette, not performance ranking.",
        "misconception": "Volume/performance equals devotion; skipping source-language layer of Śikṣāṣṭaka 1.",
        "care_boundary": "No ranking by volume; include full Śikṣāṣṭaka verse-1 source-language layer; invitation not contest.",
        "home_min": "memory line once + short attentive holy-name practice (even 1–3 minutes)",
        "next_week": "C3-W5 — The Nine Processes of Bhakti",
        "project_line": "Family holy-name etiquette card",
        "dev": "চেতোদর্পণমার্জনং ভবমহাদাবাগ্নিনির্বাপণং শ্রেয়ঃকৈরবচন্দ্রিকাবিতরণং বিদ্যাবধূজীবনম্ । আনন্দাম্বুধিবর্ধনং প্রতিপদং পূর্ণামৃতাস্বাদনং সর্বাত্মস্নপনং পরং বিজয়তে শ্রীকৃষ্ণসঙ্কীর্তনম্ ॥ ১২ ॥",
        "iast": "ceto-darpaṇa-mārjanaṁ bhava-mahā-dāvāgni-nirvāpaṇaṁ / śreyaḥ-kairava-candrikā-vitaraṇaṁ vidyā-vadhū-jīvanam / ānandāmbudhi-vardhanaṁ prati-padaṁ pūrṇāmṛtāsvādanaṁ / sarvātma-snapanaṁ paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam",
        "meaning": "All victory to śrī-kṛṣṇa-saṅkīrtana — which cleanses the mirror of the heart, extinguishes the forest fire of material existence, spreads the moonlight of good fortune, is the life of knowledge, expands the ocean of bliss, enables tasting full nectar at every step, and bathes the self — supreme.",
        "y": [
            ("Y01-NAME-JOY-MOVEMENT", "Name joy movement", "Gentle movement while echoing the holy name — soft voices welcome."),
            ("Y02-ETIQUETTE-MATCHING", "Etiquette matching", "Match listen / join / don’t mock."),
            ("Y03-MIRROR-HEART-CRAFT", "Mirror-heart craft", "Craft “clean the mirror” heart card."),
            ("Y04-ATTENTION-CARDS", "Attention cards", "Eyes soft / voice kind / no contest."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo the saṅkīrtana memory line."),
        ],
        "o": [
            ("O01-SIKSASTAKA-OBSERVATION", "Śikṣāṣṭaka / CC Antya 20.12 observation", "Full source-language layer + teaching meaning."),
            ("O02-KIRTANA-ETIQUETTE-BOARD", "Kīrtana etiquette board", "Attention practices vs performance traps."),
            ("O03-ATTENTION-VS-PERFORMANCE-SORT", "Attention vs performance sort", "Sort cards carefully."),
            ("O04-HOLY-NAME-HOME-SCENARIOS", "Holy name home scenarios", "Three family practice cases."),
            ("O05-HEART-MIRROR-DIAGRAM", "Heart-mirror diagram", "Cleansing metaphor with limits."),
            ("O06-EXIT-TICKET", "Exit ticket", "One etiquette rule + one home minute."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — home name culture", "Attention or performance pressure?"),
            ("P02-ETIQUETTE-CARD-SORT", "Etiquette card sort", "Sort ATTENTIVE / PERFORMANCE / DISRESPECT."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Child is shamed for soft chanting."),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One attentive holy-name slot for seven days."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Holy name practice + minimum version."),
        ],
        "pngs": ["kirtana-etiquette.png", "heart-mirror.png", "name-joy.png", "memory-mat.png", "parent-holy-name.png"],
        "cards_y": ["Soft voice welcome", "Yell to win", "Listen first", "Mock a singer", "Join kindly", "Phone during kīrtana"],
        "cards_o_sort": ["Attentive listening", "Volume contest", "Short sincere chant", "Shame soft voices", "Invite newcomers", "Performance ranking"],
        "parent_case": "A child chants softly and is shamed: “Louder or you’re not devoted.” Another adult starts a volume contest between siblings.",
    },
    "C3-W5": {
        "mechanic": "Nine-process wheel",
        "memory": "Nine ways to love Viṣṇu.",
        "adult_memory": "Nine processes offered to Viṣṇu/Kṛṣṇa — choose one realistic practice; no ranking.",
        "eq": "How do the nine processes map family life — with Viṣṇu/Kṛṣṇa as the object, not generic virtue?",
        "conclusion": "Nine processes of bhakti to Viṣṇu; families choose one realistic practice; never rank processes or families.",
        "misconception": "Ranking processes/families; generic virtue without Viṣṇu as object; citing 7.5.23 without 7.5.24.",
        "care_boundary": "Must include both 7.5.23 and 7.5.24; no ranking; one realistic practice.",
        "home_min": "memory line once + practice the family’s chosen process once",
        "next_week": "C3-W6 — Bhakti Mela: Kīrtana, Drama and Family Presentation",
        "project_line": "Family nine-process wheel with one chosen practice",
        "dev": "श्रीप्रह्राद उवाच श्रवणं कीर्तनं विष्णो: स्मरणं पादसेवनम् । अर्चनं वन्दनं दास्यं सख्यमात्मनिवेदनम् ॥ २३ ॥ इति पुंसार्पिता विष्णौ भक्तिश्चेन्नवलक्षणा । क्रियेत भगवत्यद्धा तन्मन्येऽधीतमुत्तमम् ॥ २४ ॥",
        "iast": "śravaṇaṁ kīrtanaṁ viṣṇoḥ smaraṇaṁ pāda-sevanam / arcanaṁ vandanaṁ dāsyaṁ sakhyam ātma-nivedanam // iti puṁsārpitā viṣṇau bhaktiś cen nava-lakṣaṇā / kriyeta bhagavaty addhā tan manye 'dhītam uttamam",
        "meaning": "Hearing, chanting, remembering, serving the Lord's feet, worship, prayer, servitude, friendship, and full surrender — nine processes of bhakti; when such bhakti is offered to Viṣṇu, that is considered the topmost learning.",
        "y": [
            ("Y01-PROCESS-PICTURE-WHEEL", "Process picture wheel", "Spin/point to nine simple picture slices — no ranking."),
            ("Y02-PROCESS-MATCHING", "Process matching", "Match hear/chant/remember pictures."),
            ("Y03-ONE-PRACTICE-CRAFT", "One-practice craft", "Choose one slice to try at home."),
            ("Y04-ENCOURAGE-CARDS", "Encourage cards", "Cheer others’ practices without ranking."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo: Nine ways to love Viṣṇu."),
        ],
        "o": [
            ("O01-SB-7-5-23-24-OBSERVATION", "ŚB 7.5.23–24 observation", "Both verses; nine names; offered to Viṣṇu."),
            ("O02-NINE-PROCESS-PLANNING", "Nine-process planning", "Plan one realistic household practice."),
            ("O03-OBJECT-VS-GENERIC-SORT", "Object vs generic sort", "Viṣṇu-object vs generic virtue."),
            ("O04-PRACTICE-SCENARIOS", "Practice scenarios", "Three busy-family practice cases."),
            ("O05-NINE-PROCESS-WHEEL-DIAGRAM", "Nine-process wheel diagram", "Wheel with center: offered to Viṣṇu."),
            ("O06-EXIT-TICKET", "Exit ticket", "Our one practice + no ranking pledge."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — realistic practice", "Which process fits our season of life?"),
            ("P02-CHOOSE-ONE-CARD-SORT", "Choose-one card sort", "Sort REALISTIC / OVERLOAD / RANKING."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Parents compete over which process is “higher.”"),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One chosen process for seven days."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Chosen process + minimum version."),
        ],
        "pngs": ["nine-process-wheel.png", "process-icons.png", "choose-one.png", "memory-mat.png", "parent-practice.png"],
        "cards_y": ["Hear", "Chant", "Remember", "Serve", "Rank friends", "Encourage"],
        "cards_o_sort": ["One small śravaṇa slot", "Do all nine perfectly", "Offer to Viṣṇu", "Generic kindness only", "Rank families", "Minimum version counts"],
        "parent_case": "Parents argue which of the nine processes is “higher” and push children to announce a competitive choice for status.",
    },
    "C3-W6": {
        "mechanic": "Drama + exhibition",
        "memory": "Offer it to Viṣṇu.",
        "adult_memory": "Bhakti Mela integrates Cycle 3 with kīrtana, short drama, and exhibition — noncompetitive.",
        "eq": "Can our family offer Cycle 3 learning to Viṣṇu with joy — without ranking?",
        "conclusion": "Review BG 5.29 · 7.7 · 4.34 · CC Antya 20.12 · ŚB 7.5.23–24 through kīrtana, drama, and presentation — no new doctrine.",
        "misconception": "Mela as talent contest; new doctrine dump; ranking presentations.",
        "care_boundary": "Integration only; noncompetitive; presentation/retrieval focus.",
        "home_min": "memory line once + one gratitude sentence for Cycle 3",
        "next_week": "C3 Utsava — Nityānanda Trayodaśī Family Utsava (local tithi EXTERNAL_OPEN)",
        "project_line": "Cycle 3 exhibition card / short drama or presentation cue",
        "dev": "श्रीप्रह्राद उवाच श्रवणं कीर्तनं विष्णो: स्मरणं पादसेवनम् । अर्चनं वन्दनं दास्यं सख्यमात्मनिवेदनम् ॥ २३ ॥ इति पुंसार्पिता विष्णौ भक्तिश्चेन्नवलक्षणा । क्रियेत भगवत्यद्धा तन्मन्येऽधीतमुत्तमम् ॥ २४ ॥",
        "iast": "śravaṇaṁ kīrtanaṁ viṣṇoḥ smaraṇaṁ pāda-sevanam / arcanaṁ vandanaṁ dāsyaṁ sakhyam ātma-nivedanam // iti puṁsārpitā viṣṇau bhaktiś cen nava-lakṣaṇā / kriyeta bhagavaty addhā tan manye 'dhītam uttamam",
        "meaning": "Bhakti Mela integrates Cycle 3 around offering bhakti to Viṣṇu with joy — retrieval and presentation, not new doctrine. (ŚB 7.5.23–24 center.)",
        "y": [
            ("Y01-MINI-DRAMA-KIRTANA", "Mini drama / kīrtana", "Short joyful scene + soft kīrtana invitation."),
            ("Y02-CYCLE3-ICON-MATCHING", "Cycle 3 icon matching", "Match five week icons."),
            ("Y03-EXHIBITION-CRAFT", "Exhibition craft", "One poster sentence: Offer it to Viṣṇu."),
            ("Y04-CHEER-CARDS", "Cheer cards", "Encourage every family."),
            ("Y05-MEMORY-PHRASE-MAT", "Memory phrase mat", "Echo: Offer it to Viṣṇu."),
        ],
        "o": [
            ("O01-CYCLE3-RETRIEVAL", "Cycle 3 retrieval", "Retrieve five primary themes."),
            ("O02-PRESENTATION-RUBRIC", "Presentation rubric", "Clarity / source / kindness / time — not polish ranking."),
            ("O03-NONCOMPETITIVE-SORT", "Noncompetitive sort", "Sort OFFERING / RANKING."),
            ("O04-DRAMA-EXHIBITION-SCENARIOS", "Drama/exhibition scenarios", "Three coaching cases."),
            ("O05-MELA-FLOW-DIAGRAM", "Mela flow diagram", "Kīrtana → drama → present → reflect."),
            ("O06-EXIT-TICKET", "Exit ticket", "One offering sentence + gratitude."),
        ],
        "p": [
            ("P01-PRIVATE-REFLECTION", "Private reflection — offering vs performing", "Where do we slip into ranking?"),
            ("P02-EXHIBITION-COACHING-CARD-SORT", "Exhibition coaching card sort", "Sort COACH / RANK / NEW DOCTRINE."),
            ("P03-SUBSTANTIAL-FAMILY-CASE", "Substantial family case", "Family wants awards for “best drama.”"),
            ("P04-HOUSEHOLD-OPERATING-APPLICATION", "Household operating application", "One noncompetitive cheer rule + offering line."),
            ("P05-PRIVATE-NEXT-STEP-SANKALPA", "Private next-step saṅkalpa", "Mela offering practice."),
        ],
        "pngs": ["mela-flow.png", "exhibition-board.png", "drama-cue.png", "memory-mat.png", "parent-exhibition.png"],
        "cards_y": ["Kīrtana joy", "Short drama", "Offer to Viṣṇu", "Trophy fight", "Cheer friends", "New doctrine dump"],
        "cards_o_sort": ["Retrieve a verse theme", "Award best family", "Kind presentation", "Invent new theology", "Timebox share", "Cheer another group"],
        "parent_case": "A family lobbies for “best drama” awards and wants to introduce a brand-new doctrinal topic during Mela instead of reviewing Cycle 3.",
    },
}

NEXT_AFTER = {
    "C2-W1": "C2-W2",
    "C2-W2": "C2-W3",
    "C2-W3": "C2-W4",
    "C2-W4": "C2-W5",
    "C2-W5": "C2-W6",
    "C2-W6": "C2-UTSAVA",
    "C3-W1": "C3-W2",
    "C3-W2": "C3-W3",
    "C3-W3": "C3-W4",
    "C3-W4": "C3-W5",
    "C3-W5": "C3-W6",
    "C3-W6": "C3-UTSAVA",
}
