#!/usr/bin/env python3
"""Week data for C2-W6 and C3-W1..C3-W6 gold packs."""
from __future__ import annotations

EXTRA_WEEKS: list[dict] = [
    dict(
        code="C2-W6",
        slug="c2-w6-integration-night-choice-consequence-and-the-modes",
        title="Integration Night: Choice, Consequence, and the Modes",
        eq="How do choice, consequence, and the modes form one coherent family practice?",
        memory="Retrieve, repair, and choose again — without ranking.",
        ref="Cycle 2 review (BG 18.63 center)",
        url="https://vedabase.io/en/library/bg/18/63/",
        iast="BG 3.9 · BG 18.63 · BG 2.22 · BG 14.5 · BG 7.14",
        meaning="Choice, consequence, and the modes must form one coherent family practice — synthesis, not new doctrine.",
        misconception="Integration night means competing to sound the most advanced.",
        next_week="Protected off-week / calendar note — then Cycle 3 begins with BG 5.29 (title only tonight).",
        home_min="Once: family names one C2 learning and one repair/choice practice without scoring anyone.",
        summary="Integration night retrieves Cycle 2: action can bind or free (BG 3.9), the next choice matters (BG 18.63), the body is temporary clothing (BG 2.22), modes color experience (BG 14.5), and māyā is hard without surrender (BG 7.14). No major new doctrine. Noncompetitive presentations.",
        core="Tonight we weave the chain. We do not add a new ontology. Families retrieve, correct misconceptions, present briefly, and choose one ongoing practice. Scoring devotion is forbidden.",
        conclusion="One coherent practice: hear, choose responsibly, remember temporariness, notice modes, seek Kṛṣṇa — without ranking.",
        script_hook="If Cycle 2 stayed as five separate posters, homes would leave with fragments. Integration asks: can these teachings speak as one family practice?",
        script_core="Walk the chain with one sentence each. Emphasize BG 18.63 as the center for tonight’s lab: deliberate, then act. Use retrieval stations, not lectures.",
        child_para="We remember five friend-ideas from Cycle 2 and practice kindness without winning trophies.",
        young_cue="Five paper beads on a string labeled with simple C2 words.",
        young_story="""> This cycle we learned: actions have fruits; the next choice matters; the body is like clothes; moods can color our day; and seeking Kṛṣṇa matters more than only decorating temporary things.  
> Tonight we string those ideas like beads. No one is better than another. We help each other remember.""",
        wonder=["Which bead do you remember?", "How can we help a friend remember?", "What is one kind choice tonight?"],
        move_name="Bead walk",
        move_steps=["Five floor spots for C2 ideas.", "Children walk gently to a called bead and say a child-friendly word.", "Freeze and say memory phrase."],
        craft_name="Retrieval bracelet",
        craft_steps=["String five paper beads.", "Draw one symbol per bead.", "Add a tag: ‘No ranking — only remembering.’"],
        older_scenarios="""Stations: (1) karma/action, (2) next choice, (3) reincarnation clothing, (4) modes, (5) māyā/decorating. At each: write one sentence + one misconception to reject.""",
        puzzle_name="Chain restore",
        puzzle_steps="Unscramble the five primary references into calendar order and state one teaching sentence each.",
        supports=[
            ("BG 3.9", "https://vedabase.io/en/library/bg/3/9/", "Work done as sacrifice frees; other work binds.", "Review only; no new karma casuistry."),
            ("BG 2.22", "https://vedabase.io/en/library/bg/2/22/", "As clothes are changed, the soul passes to another body.", "No graphic death talk with young children."),
            ("BG 14.5", "https://vedabase.io/en/library/bg/14/5/", "The living being is conditioned by sattva, rajas, tamas.", "Do not diagnose people’s modes as insults."),
            ("BG 7.14", "https://vedabase.io/en/library/bg/7/14/", "Māyā is hard; surrender crosses.", "Keep hope; no despair speech."),
        ],
        analogies=[
            ("Five beads, one string", "Separate beads fall; a stringed chain can be worn as practice.", "Do not claim the string replaces śāstra."),
            ("Orchestra rehearsal", "Integration is rehearsal of known parts, not a new symphony.", "No ranking solos."),
            ("Map legend", "Tonight redraws the legend for roads already traveled.", "No new continents of doctrine."),
        ],
        cases=[
            dict(title="Trophy night", sit="A child wants first-place sticker for ‘best spiritual answer.’", mistake="Integration is a contest.", principle="Noncompetitive rubric", response="Thank effort; refuse ranking; invite helping a peer remember.", action="Use emerging/developing/secure language only if needed — never scores.", not_say="Winner family."),
            dict(title="Fragmented dad", sit="A parent remembers only ‘modes’ and forgets responsibility/choice.", mistake="One week replaces the chain.", principle="Coherent practice", response="Gently restore BG 18.63 beside modes.", action="Write two linked sentences on one card.", not_say="You failed Cycle 2."),
            dict(title="New doctrine urge", sit="Someone wants a deep new topic tonight because energy is high.", mistake="Integration = advanced new teaching.", principle="No major new doctrine", response="Park the topic for later; finish retrieval.", action="Parking-lot sticky note.", not_say="Shutting down curiosity with sarcasm."),
        ],
        discovery=["Which week was easiest to remember?", "Which misconception still tempts us?", "What does noncompetitive mean tonight?"],
        understanding=["What is the C2 chain?", "Why is BG 18.63 a useful center for practice?", "What must we not add tonight?"],
        application=["One sentence presentation plan", "One ongoing practice", "One way to avoid ranking at home"],
        faq=[
            ("Can we teach something new?", "No major new doctrine; retrieval and synthesis only."),
            ("What if a family missed weeks?", "Welcome; give a one-sentence chain card; no shame."),
            ("How long are presentations?", "About 10 minutes/family max; drawing-only OK."),
            ("Do we grade devotion?", "Never."),
            ("What about Utsava dates?", "Calendar candidates remain subject to local confirmation (EXTERNAL_OPEN)."),
        ],
        science_reason="Integration night synthesizes prior doctrinal conclusions. No empirical study is required to justify retrieval, misconception correction, or noncompetitive family presentation.",
        scriptural_examples="""### Example A — Review chain
Walk BG 3.9 → 18.63 → 2.22 → 14.5 → 7.14 with one sentence each. Limit: no new casuistry.

### Example B — Responsibility center (BG 18.63)
Deliberate then act. Limit: do not force dramatic life announcements.""",
        devotional="Historical classroom note: founding cohorts traditionally use integration nights for retrieval and encouragement rather than examination. Keep that spirit; no invented saint anecdotes required.",
    ),
    dict(
        code="C3-W1",
        slug="c3-w1-who-is-god-the-supreme-enjoyer-proprietor-and-friend",
        title="Who Is God — the Supreme Enjoyer, Proprietor, and Friend",
        eq="If God is enjoyer, proprietor, and friend, how should our family live?",
        memory="God is enjoyer, proprietor, and friend — that knowledge brings peace.",
        ref="BG 5.29",
        url="https://vedabase.io/en/library/bg/5/29/",
        iast="bhoktāraṁ yajña-tapasāṁ sarva-loka-maheśvaram / suhṛdaṁ sarva-bhūtānāṁ jñātvā māṁ śāntim ṛcchati",
        meaning="Knowing the Lord as the enjoyer of sacrifice and austerity, the proprietor of all worlds, and the friend of all beings — one attains peace.",
        misconception="Peace means nobody is in charge, or that friendship erases God's supremacy.",
        next_week="C3-W2 Who Is Kṛṣṇa — the Supreme Personality of Godhead (BG 7.7)",
        home_min="Once: before a meal or outing, say aloud one of the three titles (enjoyer / proprietor / friend) and thank Him.",
        summary="BG 5.29 gives a peace formula: know the Lord as enjoyer of sacrifice/austerity, proprietor of all worlds, and friend of all beings. Families practice living under His ownership with friendship, not panic or denial.",
        core="Peace is not pretending nothing is owned. Peace comes from knowing who the Lord is: the enjoyer of what is offered, the proprietor of all worlds, and the friend of all beings. We neither seize His seat nor treat Him as a distant force with no friendship.",
        conclusion="Know Him as enjoyer, proprietor, and friend — walk toward peace.",
        script_hook="Many peace strategies try to empty the universe of a personal Lord. BG 5.29 does the opposite: peace comes by knowing Him rightly.",
        script_core="Teach the three titles slowly. Connect enjoyer to offering, proprietor to humility about stuff, friend to courage and warmth. Preview that personal Kṛṣṇa depth grows next week without dumping līlā tonight.",
        child_para="God enjoys what we offer, owns everything, and is our friend. Knowing that helps our hearts feel peaceful.",
        young_cue="Three paper crowns/labels: Enjoyer, Owner, Friend.",
        young_story="""> Kṛṣṇa teaches that He is the one who enjoys offerings, the owner of all places, and the friend of everyone.  
> When we remember those three truths, our hearts can become quieter.  
> We practice saying thank You to our Friend who owns everything.""",
        wonder=["Who is our Friend?", "What does owner mean?", "What can we offer with love?"],
        move_name="Three corners",
        move_steps=["Corners labeled Enjoyer / Proprietor / Friend.", "Teacher says a child example; children walk to the matching corner.", "Freeze and say memory phrase."],
        craft_name="Peace triangle",
        craft_steps=["Draw a triangle.", "Label sides Enjoyer / Proprietor / Friend.", "Decorate gently; add memory phrase."],
        older_scenarios="""1) Sibling fight over ‘my toy’ vs proprietor language. 2) Offering thanks before snack. 3) Fear that God is only judge, never friend.""",
        puzzle_name="Title match",
        puzzle_steps="Match enjoyer/proprietor/friend to three home scenes; reject a fourth false title (‘absent landlord only’).",
        supports=[
            ("BG 5.29", "https://vedabase.io/en/library/bg/5/29/", "Primary peace formula.", "Do not yet unfold full personal līlā (W2)."),
            ("BG 9.24", "https://vedabase.io/en/library/bg/9/24/", "The Lord is the enjoyer and Lord of all sacrifices.", "Keep offering language age-safe."),
            ("BG 9.18", "https://vedabase.io/en/library/bg/9/18/", "Goal, sustainer, master, witness, abode, friend…", "Sample titles only; do not dump list as quiz."),
        ],
        analogies=[
            ("Borrowed library book", "We use carefully what we do not ultimately own.", "God’s proprietorship is not a public library bureaucracy."),
            ("Host of the feast", "The host enjoys the offering of love more than grabbing food first.", "Do not trivialize yajña."),
            ("Best friend who is also principal", "Friendship does not erase authority; authority need not erase warmth.", "School analogy is limited."),
        ],
        cases=[
            dict(title="Mine reflex", sit="A child screams ‘mine’ over a shared toy.", mistake="Proprietorship language is only for adults / or ‘nothing is mine so I smash things.’", principle="BG 5.29 proprietor + friend", response="Name feelings; practice ‘Kṛṣṇa owns; we share.’", action="One share practice + thank-You line.", not_say="Selfish demon."),
            dict(title="Peace by denial", sit="An adult says peace means no one is in charge.", mistake="Peace = no proprietor.", principle="BG 5.29", response="Peace comes by knowing the Lord rightly.", action="Read three titles once at dinner.", not_say="Your philosophy is stupid."),
            dict(title="Friend only, never Lord", sit="A teen wants only ‘buddy God’ with no obedience.", mistake="Friendship erases supremacy.", principle="Enjoyer + proprietor + friend together", response="Hold all three titles.", action="Write three titles on a card.", not_say="Blind obedience threats."),
        ],
        discovery=["Which title feels newest?", "What does friend protect us from?", "What does proprietor change about ‘mine’?"],
        understanding=["What three titles does BG 5.29 give?", "What result does knowing them bring?", "How do the titles correct opposite errors?"],
        application=["One thank-You before food", "One share act", "One sentence of peace language at home"],
        faq=[
            ("Is God only energy?", "This verse teaches personal titles — enjoyer, proprietor, friend."),
            ("Does proprietor mean we own nothing practically?", "We steward; we do not seize His seat."),
            ("Why friendship matters?", "Without it, proprietorship can sound cold; the verse includes suhṛt."),
            ("Can we teach Kṛṣṇa-līlā now?", "Preview only; depth is next week."),
            ("What about other deities talk?", "Stay with this verse’s titles; defer complex comparisons."),
        ],
        science_reason="BG 5.29’s peace formula is doctrinal. Psychology studies on gratitude cannot prove God’s proprietorship or friendship.",
        scriptural_examples="""### Example A — Peace by knowing (BG 5.29)
Primary titles and result. Limit: no full purport dump.

### Example B — Enjoyer of sacrifices (BG 9.24)
Supports enjoyer title. Limit: age-safe offering language.""",
        devotional="Classroom paraphrase: devotees find peace in knowing Kṛṣṇa as master and friend together. No invented historical dialogue.",
    ),
    dict(
        code="C3-W2",
        slug="c3-w2-who-is-kṛṣṇa-the-supreme-personality-of-godhead",
        title="Who Is Kṛṣṇa — the Supreme Personality of Godhead",
        eq="If Kṛṣṇa is the Supreme, how does that change our family’s center?",
        memory="Nothing is higher than Kṛṣṇa — everything rests on Him.",
        ref="BG 7.7",
        url="https://vedabase.io/en/library/bg/7/7/",
        iast="mattaḥ parataraṁ nānyat kiñcid asti dhanañ-jaya / mayi sarvam idaṁ protaṁ sūtre maṇi-gaṇā iva",
        meaning="There is no truth superior to Kṛṣṇa; everything rests upon Him as pearls are strung on a thread.",
        misconception="All deities/paths are interchangeable equals with no Supreme Person.",
        next_week="C3-W3 Guru, Sādhu, and Śāstra (BG 4.34)",
        home_min="Once: place Kṛṣṇa’s name at the center of a short family prayer (invitation, not force).",
        summary="After knowing God as enjoyer/proprietor/friend, BG 7.7 identifies Kṛṣṇa as that Supreme Person: nothing superior; all rests on Him like pearls on a thread.",
        core="Kṛṣṇa is not one option among equals in a vague spiritual marketplace. BG 7.7 teaches there is no truth superior to Him, and the many rest on Him as pearls on one thread. We speak with respect, without invented līlā dialogue, and without contempt for persons.",
        conclusion="Center the thread — Kṛṣṇa is Supreme.",
        script_hook="Last week: enjoyer, proprietor, friend. This week: who is that Lord? Kṛṣṇa — nothing higher; all rests on Him.",
        script_core="Read BG 7.7. Use pearl-thread analogy with limit. Block both contemptuous exclusivism theater and ‘everything is the same’ erasure of the verse.",
        child_para="Kṛṣṇa is the highest. Like pearls on a string, many things rest on Him.",
        young_cue="A string with paper pearls.",
        young_story="""> Kṛṣṇa tells Arjuna there is nothing higher than Him.  
> He says everything rests on Him like pearls resting on a thread.  
> We practice putting Kṛṣṇa’s name in the middle of our thank-You.""",
        wonder=["What is a thread for?", "Who is at the center?", "What pearl can we offer (kindness)?"],
        move_name="Pearl line",
        move_steps=["Children are gentle ‘pearls’ in a line holding a soft ribbon ‘thread.’", "Walk slowly together.", "Stop and say memory phrase."],
        craft_name="Pearl-thread craft",
        craft_steps=["Cut paper pearls.", "Write kind acts on pearls.", "String them; label center tag ‘Kṛṣṇa’."],
        older_scenarios="""1) ‘All the same’ cafeteria spirituality vs BG 7.7. 2) Using supremacy talk to insult classmates. 3) Forgetting friend-title from W1 while asserting supremacy.""",
        puzzle_name="Thread center",
        puzzle_steps="Place cards around a center labeled Kṛṣṇa; reject a card that says ‘nothing is center.’",
        supports=[
            ("BG 7.7", "https://vedabase.io/en/library/bg/7/7/", "Nothing superior; pearls on a thread.", "No invented līlā."),
            ("BG 10.12–13", "https://vedabase.io/en/library/bg/10/12-13/", "Arjuna accepts Kṛṣṇa as Supreme after hearing — paraphrase carefully.", "No fabricated dialogue."),
            ("BG 5.29", "https://vedabase.io/en/library/bg/5/29/", "Carry forward enjoyer/proprietor/friend.", "Keep continuity without re-teaching whole W1."),
        ],
        analogies=[
            ("Pearls on a thread", "Many rest on one thread; remove the thread and the order falls.", "Analogy ≠ full ontology of creation."),
            ("Solar system center", "Planets relate to a center of gravity.", "Do not equate Kṛṣṇa with a ball of gas."),
            ("Necklace clasp", "The clasp holds the strand’s usefulness.", "Limited craft metaphor."),
        ],
        cases=[
            dict(title="Cafeteria equalizing", sit="A teen says every spiritual claim is equal so BG 7.7 cannot mean what it says.", mistake="The verse is only poetry with no claim.", principle="BG 7.7", response="Read the verse; discuss respectfully; no contempt for persons.", action="Write the teaching meaning once.", not_say="Your friends are demons."),
            dict(title="Weaponized supremacy", sit="A child uses ‘Kṛṣṇa is Supreme’ to insult another child’s family.", mistake="Supremacy talk licenses cruelty.", principle="Supreme + friend (BG 5.29 continuity)", response="Correct cruelty; supremacy never means meanness.", action="Apology + friend title reminder.", not_say="Public shame."),
            dict(title="Centerless week", sit="Family schedules crowd out any remembrance.", mistake="Life needs no center.", principle="Pearls need a thread", response="Choose one short center cue daily.", action="One prayer with Kṛṣṇa’s name.", not_say="You are faithless."),
        ],
        discovery=["What does ‘no superior’ mean?", "What are the pearls in our week?", "How do we speak respectfully?"],
        understanding=["What image does BG 7.7 use?", "How does this continue BG 5.29?", "What misuse must we block?"],
        application=["One center prayer", "One respectful speech act", "One schedule pearl offered to Kṛṣṇa"],
        faq=[
            ("Is this hateful toward others?", "No. Hold the verse without insulting persons."),
            ("Can we tell fancy pastimes?", "Only source-bound paraphrase; no invented dialogue."),
            ("What about impersonal ideas?", "This verse asserts a Supreme Person as the highest."),
            ("How does friendship fit?", "Carry BG 5.29 forward."),
            ("Next week?", "How we receive knowledge — guru, sādhu, śāstra."),
        ],
        science_reason="Kṛṣṇa’s supremacy in BG 7.7 is doctrinal. Cosmology analogies are pedagogy, not scientific proof of the Absolute Truth.",
        scriptural_examples="""### Example A — BG 7.7 primary
Nothing superior; pearls on a thread.

### Example B — Continuity with BG 5.29
Supreme friend/proprietor/enjoyer is Kṛṣṇa. Limit: no līlā invention.""",
        devotional="Use only authorized descriptions of Kṛṣṇa as Bhagavān; no fan-fiction pastimes.",
    ),
    dict(
        code="C3-W3",
        slug="c3-w3-guru-sādhu-and-śāstra-how-we-receive-spiritual-knowledge",
        title="Guru, Sādhu, and Śāstra — How We Receive Spiritual Knowledge",
        eq="How should our family receive spiritual knowledge without speculation?",
        memory="Approach with humility, questions, and service.",
        ref="BG 4.34",
        url="https://vedabase.io/en/library/bg/4/34/",
        iast="tad viddhi praṇipātena paripraśnena sevayā / upadekṣyanti te jñānaṁ jñāninas tattva-darśinaḥ",
        meaning="Approach those who have seen the truth — with humility, inquiry, and service — and they will instruct you in knowledge.",
        misconception="Anyone with confidence online is a guru, or asking questions is offensive.",
        next_week="C3-W4 Śrī Caitanya Mahāprabhu and the Holy Name (CC Antya 20.12)",
        home_min="Once: ask one sincere question about the week to a knowledgeable devotee/parent and listen humbly.",
        summary="BG 4.34 teaches the receiving posture: humility, inquiry, and service toward those who have seen the truth. Families practice anti-speculation habits with śāstra as standard.",
        core="Spiritual knowledge is received, not freestyled. BG 4.34 names the posture: praṇipāta (humility), paripraśna (sincere inquiry), sevā (service). Teachers who have seen the truth can instruct. We block both blind personality cults without śāstra and proud self-guru internet theater.",
        conclusion="Receive knowledge with humility, questions, and service.",
        script_hook="Last weeks named who God is. This week asks how we learn without inventing.",
        script_core="Teach the three limbs of 4.34. Connect to guru–sādhu–śāstra checks. Defer initiation details to proper authorities; do not invent local diksha policy.",
        child_para="We learn about Kṛṣṇa by asking humbly, listening, and helping — not by making things up.",
        young_cue="Three steps drawn on floor: Bow/listen, Ask, Help.",
        young_story="""> Kṛṣṇa teaches: learn from those who know the truth.  
> Come with a humble heart, ask good questions, and serve.  
> Then they can teach you. We practice asking kindly and listening.""",
        wonder=["What is a good question?", "How do we listen?", "How can we help?"],
        move_name="Three-step path",
        move_steps=["Step on Humility mat, Inquiry mat, Service mat in order.", "Say a kind question on Inquiry mat.", "Freeze and repeat memory phrase."],
        craft_name="Question card",
        craft_steps=["Fold a card.", "Write one sincere question.", "On back: ‘I will listen.’"],
        older_scenarios="""1) Influencer guru claim. 2) Fear of asking questions. 3) Ignoring śāstra because a popular speaker sounds nice.""",
        puzzle_name="Filter sort",
        puzzle_steps="Sort claims into ‘check with śāstra/sādhu/guru’ vs ‘speculation.’",
        supports=[
            ("BG 4.34", "https://vedabase.io/en/library/bg/4/34/", "Humility, inquiry, service.", "No authorization of speculative gurus."),
            ("BG 16.23–24", "https://vedabase.io/en/library/bg/16/23/", "Rejecting śāstra leads to failure; take śāstra as standard.", "Age-appropriate; no fear mongering."),
            ("BG 4.1–2", "https://vedabase.io/en/library/bg/4/1/", "Disciplic succession theme — paraphrase carefully.", "No invented lineage charts tonight."),
        ],
        analogies=[
            ("Apprentice posture", "A craft is learned by humble asking and helping, not by yelling at the master.", "Spiritual knowledge is more than a craft."),
            ("Lab safety rules", "You do not freestyle chemicals; you follow trained instruction.", "Do not reduce bhakti to lab class."),
            ("Map + guide + local hikers", "Śāstra map, guru guide, sādhu confirmation.", "Analogy limited; not institutional politics."),
        ],
        cases=[
            dict(title="Influencer diksha", sit="A teen treats a charismatic online speaker as absolute authority without śāstra checks.", mistake="Confidence = tattva-darśī.", principle="BG 4.34 + śāstra standard", response="Appreciate seeking; require checks; defer formal initiation questions.", action="Compare one claim to a verse with a parent.", not_say="Your favorite speaker is demonic."),
            dict(title="Question shame", sit="A child thinks asking means weak faith.", mistake="Inquiry is offensive.", principle="paripraśna is part of the verse", response="Praise sincere questions.", action="Write one question card.", not_say="Stop interrupting with doubts."),
            dict(title="Service-free demand", sit="Someone wants advanced answers while refusing any helpful service posture.", mistake="Knowledge is a product we purchase with curiosity alone.", principle="sevā accompanies receiving", response="Invite a small practical help step.", action="One help task + one question.", not_say="You are disqualified forever."),
        ],
        discovery=["What are the three limbs?", "Why does speculation fail families?", "Who can we ask safely this week?"],
        understanding=["What does BG 4.34 promise?", "How do guru, sādhu, and śāstra work together?", "What is not authorized tonight?"],
        application=["One humble ask", "One listening practice", "One small service act"],
        faq=[
            ("Who is my guru?", "Do not invent policy; encourage authorized local guidance and śāstra."),
            ("Are questions bad?", "Sincere inquiry is in the verse."),
            ("What about bad leaders?", "Śāstra and sādhu checks matter; report safety issues to parents/owner."),
            ("Is service chores only?", "Service includes helpful, respectful assistance in learning environments."),
            ("Next week?", "Holy name and Śrī Caitanya Mahāprabhu."),
        ],
        science_reason="The epistemology of receiving transcendental knowledge via BG 4.34 is doctrinal. Educational psychology about questioning cannot prove tattva-darśī realization.",
        scriptural_examples="""### Example A — BG 4.34
Humility, inquiry, service.

### Example B — Śāstra as standard (BG 16.23–24)
Anti-speculation support. Limit: no fear-based teaching.""",
        devotional="Mention the principle of learning from realized devotees and śāstra; do not invent private guru stories for the cohort.",
    ),
    dict(
        code="C3-W4",
        slug="c3-w4-śrī-caitanya-mahāprabhu-and-the-holy-name",
        title="Śrī Caitanya Mahāprabhu and the Holy Name",
        eq="How does śrī-kṛṣṇa-saṅkīrtana cleanse and give life to our family?",
        memory="All victory to śrī-kṛṣṇa-saṅkīrtana.",
        ref="CC Antya 20.12 / Śikṣāṣṭaka 1",
        url="https://vedabase.io/en/library/cc/antya/20/12/",
        iast="ceto-darpaṇa-mārjanaṁ bhava-mahā-dāvāgni-nirvāpaṇaṁ śreyaḥ-kairava-candrikā-vitaraṇaṁ vidyā-vadhū-jīvanam ānandāmbudhi-vardhanaṁ prati-padaṁ pūrṇāmṛtāsvādanaṁ sarvātma-snapanaṁ paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam",
        meaning="Let there be victory for śrī-kṛṣṇa-saṅkīrtana — chanting that cleanses the heart's mirror, extinguishes material misery's forest fire, spreads the moonlight of good fortune, is the life of true knowledge, expands the ocean of bliss, and gives full nectar at every step.",
        misconception="Chanting is only mood music, or volume/force proves advancement.",
        next_week="C3-W5 The Nine Processes of Bhakti (ŚB 7.5.23–24)",
        home_min="Once: invite (never force) three soft mahā-mantra recitations together.",
        summary="CC Antya 20.12 presents the complete Śikṣāṣṭaka 1 verse ending in paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam. Families honor Śrī Caitanya Mahāprabhu’s emphasis on the holy name without invented dialogue or forced chanting.",
        core="The complete verse glorifies śrī-kṛṣṇa-saṅkīrtana from cleansing the heart’s mirror through victory. We chant by invitation, with respect, without punishment volume contests, and without stopping the verse at the first half.",
        conclusion="All victory to śrī-kṛṣṇa-saṅkīrtana — invite, do not force.",
        script_hook="We received knowledge posture last week. This week we meet the holy name through Śrī Caitanya Mahāprabhu’s Śikṣāṣṭaka 1 as given in CC Antya 20.12 — complete through paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam.",
        script_core="Read the full IAST in two breaths if needed; never truncate before the victory line. Explain mirror / forest fire / moonlight images gently. Practice soft chanting invitation.",
        child_para="Chanting Kṛṣṇa’s names can clean our hearts like wiping a mirror. We sing softly together — nobody is forced.",
        young_cue="A small hand mirror prop (safe plastic) and a soft ‘wipe’ cloth.",
        young_story="""> Śrī Caitanya Mahāprabhu taught the glories of chanting Kṛṣṇa’s names.  
> The verse says saṅkīrtana cleans the heart’s mirror and brings victory.  
> We practice a few soft names together. If someone wants to listen quietly, that is OK.""",
        wonder=["What does a clean mirror show?", "What names can we say softly?", "How do we invite friends kindly?"],
        move_name="Mirror wipe walk",
        move_steps=["Children take gentle wipe motions in the air while walking a circle.", "Stop and whisper ‘Hare Kṛṣṇa’ once if willing.", "Freeze; say memory phrase."],
        craft_name="Mirror heart card",
        craft_steps=["Draw a mirror shape.", "Write ‘clean heart’ inside.", "Add ‘paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam’ sticker/line for teachers to help."],
        older_scenarios="""1) Forced loud chanting as punishment. 2) Treating kīrtana as entertainment only. 3) Stopping the verse at vidyā-vadhū-jīvanam and missing the victory line.""",
        puzzle_name="Complete the verse",
        puzzle_steps="Order half-verse cards so the final card is paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam.",
        supports=[
            ("CC Antya 20.12", "https://vedabase.io/en/library/cc/antya/20/12/", "Complete Śikṣāṣṭaka 1.", "No invented Caitanya dialogue."),
            ("CC Adi 7.83", "https://vedabase.io/en/library/cc/adi/7/83/", "Nature of the mahā-mantra — develops loving attachment.", "Invitation only."),
            ("Lecture on Mahā-mantra", "https://vedabase.io/en/library/transcripts/660909le-new-york/", "Authoritative statement of the sixteen-word mahā-mantra.", "Temple sheet may control exact local text."),
        ],
        analogies=[
            ("Mirror cleaning", "Dirt blocks clear seeing; cleansing reveals.", "Do not claim mechanical wiping equals full realization."),
            ("Forest fire hose", "Saṅkīrtana cools blazing material misery.", "Avoid scary fire talk with K–2."),
            ("Moonlight on lotus", "Auspiciousness spreads gently.", "Poetic pedagogy."),
        ],
        cases=[
            dict(title="Punishment kīrtana", sit="An adult threatens extra loud rounds as punishment.", mistake="Force volume = advancement.", principle="Invitation; CC Antya 20.12 glories", response="Stop punishment framing; invite soft practice.", action="Three soft mantras optional.", not_say="Chant or else."),
            dict(title="Half-verse pack", sit="A printout ends at vidyā-vadhū-jīvanam.", mistake="First half is the whole verse.", principle="Complete Antya 20.12", response="Replace with full verse through paraṁ vijayate…", action="Correct handout.", not_say="It’s close enough forever."),
            dict(title="Entertainment only", sit="Youth treat kīrtana as hype music with no heart meaning.", mistake="Only mood, no cleansing glory.", principle="ceto-darpaṇa-mārjanam…", response="Keep joy; add one meaning line.", action="Read one image from the verse.", not_say="You are fake devotees."),
        ],
        discovery=["What does the victory line say?", "Which image helps you most?", "How do we invite without forcing?"],
        understanding=["Why must the verse be complete?", "What is saṅkīrtana?", "What misuse of chanting do we block?"],
        application=["Three soft mantras once", "One meaning image shared", "One invitation practice at home"],
        faq=[
            ("Must everyone chant loudly?", "No. Invitation only; listening respectfully is allowed."),
            ("Is our meaning a BBT translation?", "No — KUTUMBA teaching meaning; Sanskrit from VedaBase."),
            ("Who is Śrī Caitanya?", "Teach from authorized sources only; no invented stories."),
            ("Mahā-mantra source?", "See opening mantras handout URLs."),
            ("Next week?", "Nine processes of bhakti."),
        ],
        science_reason="The glories of śrī-kṛṣṇa-saṅkīrtana in CC Antya 20.12 are doctrinal/devotional claims. Music-therapy studies cannot prove the verse’s transcendental effects.",
        scriptural_examples="""### Example A — Complete CC Antya 20.12
Include through paraṁ vijayate śrī-kṛṣṇa-saṅkīrtanam.

### Example B — Mahā-mantra lecture URL
Support chanting practice with authoritative source links.""",
        devotional="Śrī Caitanya Mahāprabhu’s Śikṣāṣṭaka is received through authorized CC text. No invented pastimes.",
    ),
    dict(
        code="C3-W5",
        slug="c3-w5-the-nine-processes-of-bhakti",
        title="The Nine Processes of Bhakti",
        eq="Which of the nine processes can our family practice this week without overload?",
        memory="Hearing and chanting come first — nine doors of bhakti.",
        ref="ŚB 7.5.23–24",
        url="https://vedabase.io/en/library/sb/7/5/23-24/",
        iast="śravaṇaṁ kīrtanaṁ viṣṇoḥ smaraṇaṁ pāda-sevanam / arcanaṁ vandanaṁ dāsyaṁ sakhyam ātma-nivedanam // iti puṁsārpitā viṣṇau bhaktiś cen nava-lakṣaṇā / kriyeta bhagavaty addhā tan manye ’dhītam uttamam",
        meaning="Prahlāda lists nine processes of bhakti unto Viṣṇu — hearing, chanting, remembering, serving the Lord's feet, worship, prayers, servitude, friendship, and full self-surrender — and teaches that such dedicated bhakti is the topmost learning.",
        misconception="Children must master all nine at once to be real devotees.",
        next_week="C3-W6 Bhakti Mela — review chain and family presentation",
        home_min="Pick one of the nine (usually hearing or chanting) and practice it once together.",
        summary="ŚB 7.5.23–24 lists nine processes and declares such dedicated bhakti the topmost learning. Families map the nine without requiring mastery of all nine.",
        core="Verse 23 lists nine processes; verse 24 teaches that bhakti offered to Viṣṇu with these characteristics is the topmost learning. We need both verses. We start where we are — often śravaṇam and kīrtanam — without shame about not doing all nine.",
        conclusion="Nine processes; begin with hearing and chanting; both verses matter.",
        script_hook="Last week: victory of saṅkīrtana. This week: Prahlāda’s map of nine processes — complete 23 and 24.",
        script_core="Read both IAST layers. Count nine on fingers. Emphasize verse 24’s ‘topmost learning.’ Choose one family focus.",
        child_para="Prahlāda teaches nine ways to love Viṣṇu/Kṛṣṇa. We can start with hearing and chanting.",
        young_cue="Nine paper doors or stepping stones.",
        young_story="""> Prahlāda taught nine ways to serve the Lord: hearing, chanting, remembering, and more.  
> He said this kind of bhakti is the best learning.  
> Tonight we practice hearing and soft chanting. We do not have to do all nine today.""",
        wonder=["Which door is hearing?", "Which is chanting?", "Which one door can we try at home?"],
        move_name="Nine-stone hop",
        move_steps=["Nine safe floor markers.", "Hop only to Hear and Chant markers today.", "Say memory phrase."],
        craft_name="Nine-door strip",
        craft_steps=["Make a strip with nine labeled doors.", "Star Hear + Chant.", "Take home."],
        older_scenarios="""1) Overwhelm — must do all nine. 2) Ignoring verse 24. 3) Using ‘dāsya’ language to bully siblings.""",
        puzzle_name="Nine + topmost",
        puzzle_steps="Match nine Sanskrit terms to English; place verse-24 card as ‘topmost learning’ capstone.",
        supports=[
            ("ŚB 7.5.23–24", "https://vedabase.io/en/library/sb/7/5/23-24/", "Nine processes + topmost learning.", "Both verses required."),
            ("CC Antya 20.12", "https://vedabase.io/en/library/cc/antya/20/12/", "Saṅkīrtana glory supports hearing/chanting priority.", "Keep continuity."),
            ("BG 9.14", "https://vedabase.io/en/library/bg/9/14/", "Constantly chanting and striving with devotion — paraphrase.", "No overload."),
        ],
        analogies=[
            ("Nine doors, one house", "Many entrances; you can enter by the nearest door today.", "Do not imply doors are unequal forever."),
            ("Piano scales", "You need not play every scale on day one.", "Bhakti is not a performance exam."),
            ("Map legend", "Verse 23 is legend; verse 24 is the destination note.", "Pedagogy."),
        ],
        cases=[
            dict(title="All-nine panic", sit="A parent prints all nine as nightly mandatory checklist.", mistake="All nine or failure.", principle="Begin with hearing/chanting; no overload", response="Pick one focus; keep joy.", action="One process once.", not_say="Lazy devotees."),
            dict(title="Missing 24", sit="Handout lists only the nine nouns.", mistake="23 alone is the full primary.", principle="Include verse 24", response="Add topmost-learning line.", action="Correct packet.", not_say="Nobody reads verse 24 anyway."),
            dict(title="Servitude bullying", sit="Older sibling demands younger ‘be my servant for bhakti.’", mistake="Dāsya means dominating people.", principle="Service to the Lord, not bullying", response="Stop; teach respectful help.", action="Repair + shared hearing.", not_say="Public humiliation."),
        ],
        discovery=["How many processes?", "What does verse 24 add?", "Which process fits our home this week?"],
        understanding=["List the nine in simple English", "Why both verses?", "What overload error do we block?"],
        application=["Choose one process", "Schedule one practice", "Help one sibling kindly"],
        faq=[
            ("Must we do all nine?", "No. Begin appropriately; often hearing and chanting."),
            ("Why verse 24?", "It teaches dedicated bhakti is topmost learning."),
            ("Sanskrit hard for kids?", "Use English doors; introduce Sanskrit gradually."),
            ("Is friendship with God casual?", "Sakhyam is sacred; teach respect."),
            ("Next week?", "Bhakti Mela integration."),
        ],
        science_reason="The nine processes and their status as topmost learning are doctrinal. Habit trackers cannot prove ŚB 7.5.23–24.",
        scriptural_examples="""### Example A — Both verses
Include 23 and 24 completely.

### Example B — Continuity with saṅkīrtana
Hearing/chanting remain central doorways.""",
        devotional="Prahlāda’s teaching is received from ŚB; paraphrase only; no invented childhood dialogues beyond śāstra.",
    ),
    dict(
        code="C3-W6",
        slug="c3-w6-bhakti-mela-kīrtana-drama-and-family-presentation",
        title="Bhakti Mela — Kīrtana, Drama, and Family Presentation",
        eq="How do we celebrate the Cycle 3 chain without ranking devotion?",
        memory="Celebrate the chain — no trophies for bhakti.",
        ref="Cycle 3 review (BG 5.29 · BG 7.7 · BG 4.34 · CC Antya 20.12 · ŚB 7.5.23–24)",
        url="https://vedabase.io/en/library/sb/7/5/23-24/",
        iast="BG 5.29 · BG 7.7 · BG 4.34 · CC Antya 20.12 · ŚB 7.5.23–24",
        meaning="Bhakti Mela — celebrate the C3 chain (God as enjoyer/friend, Kṛṣṇa as Supreme, guru-sādhu-śāstra, śrī-kṛṣṇa-saṅkīrtana, nine processes) with family presentation and without ranking.",
        misconception="Mela night is a competition or a time to invent new doctrine.",
        next_week="Follow calendar for off weeks / next cycle planning — local Utsava confirmation remains EXTERNAL_OPEN.",
        home_min="Once: family shares one C3 gratitude and one ongoing practice without scoring.",
        summary="Bhakti Mela retrieves the exact C3 chain — including CC Antya 20.12, never a generic ‘holy name’ placeholder — and celebrates with kīrtana/drama/presentation without ranking.",
        core="Exact chain: BG 5.29 · BG 7.7 · BG 4.34 · CC Antya 20.12 · ŚB 7.5.23–24. No new major doctrine. Soft kīrtana by invitation. Presentations noncompetitive.",
        conclusion="Celebrate the exact chain with joy and humility.",
        script_hook="Tonight is mela: retrieve, rejoice, present — not examine.",
        script_core="Post the exact chain on the wall. Lead short invited kīrtana. Family presentations ~10 minutes max. Rubric without scores.",
        child_para="We celebrate five big learnings with singing and sharing. Nobody wins a trophy for loving Kṛṣṇa.",
        young_cue="Five festival flags with chain labels.",
        young_story="""> We learned: God is enjoyer, owner, and friend; Kṛṣṇa is Supreme; we learn with humility; saṅkīrtana is glorious; and there are nine ways of bhakti.  
> Tonight we celebrate like a small festival. We help each other. We do not rank friends.""",
        wonder=["Which flag do you like?", "How do we share kindly?", "What song can we invite?"],
        move_name="Flag parade",
        move_steps=["Gentle parade with paper flags.", "Stop at each chain station.", "Memory phrase."],
        craft_name="Mela flag",
        craft_steps=["Make one flag for a chosen chain link.", "Write a thank-You.", "Wave softly in parade."],
        older_scenarios="""Stations for each chain link with one misconception to reject; prepare a 2-minute family share.""",
        puzzle_name="Exact chain order",
        puzzle_steps="Order five references exactly; reject a card that says only ‘holy name’ instead of CC Antya 20.12.",
        supports=[
            ("BG 5.29", "https://vedabase.io/en/library/bg/5/29/", "Enjoyer, proprietor, friend.", "Review only."),
            ("BG 7.7", "https://vedabase.io/en/library/bg/7/7/", "Kṛṣṇa supreme.", "Review only."),
            ("BG 4.34", "https://vedabase.io/en/library/bg/4/34/", "Humility, inquiry, service.", "Review only."),
            ("CC Antya 20.12", "https://vedabase.io/en/library/cc/antya/20/12/", "Complete saṅkīrtana verse.", "Exact reference required."),
            ("ŚB 7.5.23–24", "https://vedabase.io/en/library/sb/7/5/23-24/", "Nine processes + topmost learning.", "Both verses."),
        ],
        analogies=[
            ("Festival not exam", "Mela is celebration of known dishes, not a chef competition.", "Do not trivialize bhakti."),
            ("Relay baton", "Each week passes a baton; tonight we hold the whole relay string.", "No new race."),
            ("Choir blend", "Many voices; no solo trophy.", "Invitation volume only."),
        ],
        cases=[
            dict(title="Trophy mela", sit="Someone brings ribbons for best presentation.", mistake="Ranking devotion", principle="Noncompetitive mela", response="Remove ribbons; thank all.", action="Appreciation circle.", not_say="Winner family."),
            dict(title="Generic holy-name card", sit="A poster says ‘holy name’ instead of CC Antya 20.12.", mistake="Vague chain slot", principle="Exact CC Antya 20.12", response="Correct the poster.", action="Rewrite label.", not_say="Pedantic attack on kids."),
            dict(title="New doctrine surge", sit="Guest wants a brand-new advanced topic mid-mela.", mistake="Mela = new seminar", principle="No major new doctrine", response="Parking lot; finish celebration.", action="Sticky note deferral.", not_say="Sarcasm."),
        ],
        discovery=["What is the exact chain?", "What replaces trophies?", "How do we invite kīrtana?"],
        understanding=["Why CC Antya 20.12 must be named?", "What is mela for?", "What stays EXTERNAL_OPEN on calendar?"],
        application=["Family share plan", "One ongoing practice", "One appreciation without comparison"],
        faq=[
            ("Can we score presentations?", "No."),
            ("Must everyone chant?", "Invitation only."),
            ("Is the chain flexible?", "Keep exact references; do not replace CC Antya 20.12 with ‘holy name’."),
            ("Missed weeks?", "Welcome; give chain card."),
            ("Utsava date?", "Local confirmation EXTERNAL_OPEN."),
        ],
        science_reason="Mela night is retrieval and celebration of doctrinal chain items. No empirical metric of devotion is appropriate or required.",
        scriptural_examples="""### Example A — Exact C3 chain
BG 5.29 · BG 7.7 · BG 4.34 · CC Antya 20.12 · ŚB 7.5.23–24.

### Example B — Noncompetitive presentation
Share learning; no ranking.""",
        devotional="Keep festival joy aligned with authorized kīrtana culture; no invented drama scripts about sacred persons beyond source-bound paraphrase.",
    ),
]
