#!/usr/bin/env python3
"""Forensic audit of first-six-month module content depth."""

from __future__ import annotations

import csv
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
WEEKLY = REPO / "11-weekly-program-library" / "first-six-months"
EVIDENCE = REPO / "build-evidence"
from module_utils import iter_modules  # noqa: E402

DELIVERY_FILES = [
    "complete-week.md", "overview.md", "learning-outcomes.md", "prem-ki-katha.md",
    "parent-lesson.md", "analogy-and-application.md", "questions.md", "bhakti-lab.md",
    "family-home-practice.md", "facilitator-guide.md", "materials.md", "assessment.md",
    "newcomer-adaptation.md", "risks-and-sensitive-points.md", "worksheet.md",
    "slide-outline.md", "children/lesson.md",
]

DOMAINS = [
    "analogy", "materials", "newcomer", "children", "assessment", "bhakti_lab",
    "parent_lesson", "research_layer", "lala_lali", "kisora_kisori", "visuals",
    "gamma", "claims", "sources",
]

EMPTY_PATTERNS = [
    re.compile(r"\|\s*\*\*Analogy\*\*\s*\|\s*\*\*Practical family example\*\*\s*\|\s*\n\|\s*---\s*\|\s*---\s*\|\s*\Z"),
    re.compile(r"\|\s*\*\*Materials A\*\*\s*\|\s*\*\*Materials B\*\*\s*\|\s*\n\|\s*---\s*\|\s*---\s*\|\s*\Z"),
    re.compile(r"\|\s*\*\*KUTUMBA Setu application\*\*\s*\|\s*\n\|\s*---\s*\|\s*\Z"),
    re.compile(r"\|\s*\*\*Key verse\*\*\s*\|\s*\n\|\s*---\s*\|\s*\Z"),
    re.compile(r"\|\s*\*\*Competency check\*\*\s*\|\s*\n\|\s*---\s*\|\s*\Z"),
]


def classify_file(path: Path) -> str:
    if not path.exists():
        return "missing"
    text = path.read_text(encoding="utf-8")
    body = re.sub(r"^---.*?---\s*", "", text, count=1, flags=re.DOTALL).strip()
    if len(body) < 40:
        return "empty"
    for pat in EMPTY_PATTERNS:
        if pat.search(body):
            return "empty_shell"
    lines = [ln.strip() for ln in body.splitlines() if ln.strip() and not ln.strip().startswith("---")]
    if len(lines) < 4:
        return "thin"
    return "complete"


def week_code(folder: Path) -> str:
    m = re.match(r"^(c\d+-w\d+)", folder.name)
    if not m:
        return folder.name
    p = m.group(1).split("-")
    return f"C{p[0][1:]}-W{p[1][1:].upper()}" if len(p) == 2 else folder.name


def audit_module(folder: Path) -> dict:
    row = {"module_id": week_code(folder), "folder": folder.name}
    blanks = []
    for f in DELIVERY_FILES:
        status = classify_file(folder / f.replace("/", "\\") if "/" not in f else folder / Path(f))
        key = f.replace("/", "_").replace(".md", "")
        row[key] = status
        if status in ("empty", "empty_shell", "missing", "thin"):
            blanks.append(f)
    row["blank_sections"] = "; ".join(blanks)
    row["blank_count"] = len(blanks)
    row["has_research"] = (folder / "research" / "RESEARCH-DOSSIER.md").exists()
    row["has_lala_lali"] = (folder / "children" / "lala-lali-lesson.md").exists()
    row["has_kisora"] = (folder / "children" / "kisora-kisori-lesson.md").exists()
    row["has_visuals"] = (folder / "visuals" / "VISUAL-PLAN.md").exists()
    row["has_gamma"] = (folder / "gamma" / "GAMMA-MASTER-DECK-BRIEF.md").exists()
    if "Age 4-6" in (folder / "children" / "lesson.md").read_text(encoding="utf-8") if (folder / "children" / "lesson.md").exists() else "":
        row["age_model"] = "legacy-3-band"
    else:
        row["age_model"] = "unknown"
    return row


def update_review_status(folder: Path, needs_enhancement: bool) -> None:
    rs = folder / "review-status.yaml"
    if not rs.exists():
        return
    text = rs.read_text(encoding="utf-8")
    if needs_enhancement and "weekly_derivative_pack: complete" in text:
        text = text.replace("weekly_derivative_pack: complete", "weekly_derivative_pack: enhancement-required")
        rs.write_text(text, encoding="utf-8")


def main() -> None:
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    rows = [audit_module(d) for d in iter_modules(WEEKLY)]
    for r in rows:
        update_review_status(WEEKLY / r["folder"], r["blank_count"] > 3 or not r["has_research"])

    csv_path = EVIDENCE / "EMPTY-AND-THIN-SECTIONS.csv"
    if rows:
        with csv_path.open("w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            w.writeheader()
            w.writerows(rows)

    dash_lines = [
        "# Week Quality Dashboard",
        "",
        f"Generated by `scripts/curriculum/audit_empty_sections.py`",
        "",
        "| Module | Blanks | Research | Lāla–Lālī | Kiśora–Kiśorī | Visuals | Gamma | Age model |",
        "|---|---:|---|---|---|---|---|---|",
    ]
    for r in rows:
        dash_lines.append(
            f"| {r['module_id']} | {r['blank_count']} | {'yes' if r['has_research'] else 'no'} | "
            f"{'yes' if r['has_lala_lali'] else 'no'} | {'yes' if r['has_kisora'] else 'no'} | "
            f"{'yes' if r['has_visuals'] else 'no'} | {'yes' if r['has_gamma'] else 'no'} | {r['age_model']} |"
        )

    audit_md = [
        "# First Six-Month Content Audit",
        "",
        "## Summary",
        "",
        f"- Modules audited: {len(rows)}",
        f"- Modules with 3+ blank/thin delivery files: {sum(1 for r in rows if r['blank_count'] > 3)}",
        f"- Modules missing research layer: {sum(1 for r in rows if not r['has_research'])}",
        "",
        "## Finding",
        "",
        "Structural derivative packs exist but many component files are empty table shells "
        "extracted from the monolith without substantive fill. `weekly_derivative_pack` corrected to "
        "`enhancement-required` where applicable.",
        "",
        "See `EMPTY-AND-THIN-SECTIONS.csv` and `WEEK-QUALITY-DASHBOARD.md`.",
    ]
    (EVIDENCE / "FIRST-SIX-MONTH-CONTENT-AUDIT.md").write_text("\n".join(audit_md) + "\n", encoding="utf-8")
    (EVIDENCE / "WEEK-QUALITY-DASHBOARD.md").write_text("\n".join(dash_lines) + "\n", encoding="utf-8")
    print(f"Audited {len(rows)} modules")


if __name__ == "__main__":
    main()
