#!/usr/bin/env python3
"""Build enhanced week quality dashboard with depth metrics."""

from __future__ import annotations

import csv
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
WEEKLY = REPO / "11-weekly-program-library" / "first-six-months"
EVIDENCE = REPO / "build-evidence"

from module_utils import iter_modules, module_count  # noqa: E402


def week_code(name: str) -> str:
    m = re.match(r"(c\d-w\d+)", name)
    return m.group(1).upper().replace("c", "C").replace("-w", "-W") if m else name


def word_count(path: Path) -> int:
    if not path.exists():
        return 0
    return len(re.findall(r"\b\w+\b", path.read_text(encoding="utf-8")))


def line_count(path: Path) -> int:
    return len(path.read_text(encoding="utf-8").splitlines()) if path.exists() else 0


def gamma_cards(path: Path) -> int:
    if not path.exists():
        return 0
    return len(re.findall(r"### Card \d+", path.read_text(encoding="utf-8")))


def depth_status(d: Path, rs: dict) -> str:
    pack = rs.get("weekly_derivative_pack", "unknown")
    if d.name == "c1-w2-i-am-not-this-body":
        return "gold-pilot"
    if pack == "enhancement-complete":
        return "deepened"
    if pack == "baseline-scaffold":
        return "baseline-scaffold"
    return pack


def audit_row(d: Path) -> dict:
    rs_path = d / "review-status.yaml"
    rs = {}
    if rs_path.exists():
        for line in rs_path.read_text(encoding="utf-8").splitlines():
            if ":" in line:
                k, _, v = line.partition(":")
                rs[k.strip()] = v.strip()
    claims = len(re.findall(r"-CLM-\d+", (d / "research" / "CLAIM-REGISTER.yaml").read_text(encoding="utf-8"))) if (d / "research" / "CLAIM-REGISTER.yaml").exists() else 0
    prem_wc = word_count(d / "prem-ki-katha.md")
    prem_status = "authentic" if prem_wc >= 600 and (d / "katha" / "KATHA-SOURCE-REGISTER.yaml").exists() else ("hook-only" if prem_wc < 200 else "partial")
    lala = line_count(d / "children" / "lala-lali-lesson.md")
    kisora = line_count(d / "children" / "kisora-kisori-lesson.md")
    age_model = "two-group" if lala >= 70 and kisora >= 70 else "thin"
    legacy = "preserved" if (d / "children" / "lesson.md").exists() else "none"
    thin_files = []
    for rel in ["materials.md", "newcomer-adaptation.md", "parent-lesson.md"]:
        p = d / rel
        if line_count(p) < 20:
            thin_files.append(rel)
    return {
        "module_id": week_code(d.name),
        "depth_status": depth_status(d, rs),
        "review_status": rs.get("weekly_derivative_pack", ""),
        "claims": claims,
        "gamma_cards": gamma_cards(d / "gamma" / "GAMMA-PARENT-DECK-PROMPT.md"),
        "prem_katha_status": prem_status,
        "prem_words": prem_wc,
        "lala_lines": lala,
        "kisora_lines": kisora,
        "age_model_active": age_model,
        "legacy_lesson_md": legacy,
        "dossier_lines": line_count(d / "research" / "RESEARCH-DOSSIER.md"),
        "thin_files": "; ".join(thin_files) if thin_files else "",
        "media_index": "yes" if (d / "audio-video" / "MEDIA-INDEX.yaml").exists() else "no",
    }


def main() -> int:
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    rows = [audit_row(d) for d in iter_modules(WEEKLY)]
    csv_path = EVIDENCE / "EMPTY-AND-THIN-SECTIONS.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()) if rows else [])
        w.writeheader()
        w.writerows(rows)

    dash = [
        "# Week Quality Dashboard",
        "",
        "Generated by `scripts/curriculum/build_week_quality_dashboard.py`",
        "",
        "| Module | Depth | Claims | Gamma cards | Prem-kī-Kathā | Lāla | Kiśora | Age | Dossier | Media |",
        "|---|---|---:|---:|---|---:|---:|---|---:|---|",
    ]
    for r in rows:
        dash.append(
            f"| {r['module_id']} | {r['depth_status']} | {r['claims']} | {r['gamma_cards']} | "
            f"{r['prem_katha_status']} ({r['prem_words']}w) | {r['lala_lines']} | {r['kisora_lines']} | "
            f"{r['age_model_active']} | {r['dossier_lines']} | {r['media_index']} |"
        )
    (EVIDENCE / "WEEK-QUALITY-DASHBOARD.md").write_text("\n".join(dash) + "\n", encoding="utf-8")

    audit_md = f"""# First Six-Month Content Audit

## Summary

- Modules: {len(rows)}
- Gold/deepened: {sum(1 for r in rows if r['depth_status'] in ('gold-pilot', 'deepened'))}
- Authentic Prem-kī-Kathā: {sum(1 for r in rows if r['prem_katha_status'] == 'authentic')}
- Two-group age model active: {sum(1 for r in rows if r['age_model_active'] == 'two-group')}

## Method

Active age model from Lāla–Lālī and Kiśora–Kiśorī lesson line counts. Legacy `children/lesson.md` reported separately.

See `EMPTY-AND-THIN-SECTIONS.csv` and `WEEK-QUALITY-DASHBOARD.md`.
"""
    (EVIDENCE / "FIRST-SIX-MONTH-CONTENT-AUDIT.md").write_text(audit_md, encoding="utf-8")
    print(f"Dashboard built for {len(rows)} modules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
